causeway:
  testing:
    fixtures:
      initial-script: petclinicapp.webapp.application.fixture.scenarios.PetclinicAppDemo

  viewer:
    wicket:
      prompt-style: inline
      #dialog-mode: modal
      dialog-mode-for-menu: sidebar
